CREATE DATABASE VENTA_BOLETOS
USE VENTA_BOLETOS

CREATE TABLE EMPRESA(
IDEMPRESA INT PRIMARY KEY ,
NOMBREEMPRESA VARCHAR(40) NOT NULL,
TIPOEMPRESA VARCHAR(40) NOT NULL
)
CREATE TABLE EMPLEADO(
IDEMPLEADO INT PRIMARY KEY,
NOMBREEMPLEADO VARCHAR(40) NOT NULL,
APELLIDOEMPLEADO VARCHAR(40) NOT NULL,
CELULAR INT NOT NULL,
DISTRITO VARCHAR(50) NOT NULL,
CARGO VARCHAR(50)NOT NULL
)

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY,
NOMBRECLIENTE VARCHAR(50) NOT NULL,
APELLIDOCLIENTE VARCHAR(90) NOT NULL,
CELULARCLIENTE INT NOT NULL,
DISTRITO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(40) NOT NULL
)

CREATE TABLE VENTA(
IDVENTA INT PRIMARY KEY,
DESTINO VARCHAR(100) NOT NULL,
PRECIO FLOAT NOT NULL,
TIEMPOMIN INT NOT NULL
)

SELECT * FROM EMPRESA
SELECT * FROM EMPLEADO
SELECT * FROM CLIENTE
SELECT * FROM venta

